create table folders (
	id integer primary key generated by default as identity,
	folder_name text not null
);

create table notes (
	id integer primary key generated by default as identity,
	note_name text not null,
	modified TIMESTAMPTZ not null default now(),
	folder_id integer references folders(id) on delete cascade not null,
	content text
);